using System.Text;
using DbDataBuild.Models;

namespace DbDataBuild.Targets.Rendering;

public sealed record ManifestOperation(
    string Name, bool IsDefault, string Strategy, string Matrix, IReadOnlyList<string> Findings,
    string ScriptFile, string ScriptSha256, string? ResolverFile, string? ResolverSha256, IReadOnlyList<RenderedParameter> Parameters);

/// <summary>Deterministic manifest.yml for a rendered model and target: operations, parameters, sources, hashes and matrix status (DESIGN.md 6.6). No timestamps.</summary>
public static class ManifestWriter
{
    public static string Write(string model, string target, string definitionHash,
        IReadOnlyList<string> sources, IReadOnlyList<ManifestOperation> operations)
    {
        var sb = new StringBuilder();
        sb.Append("# Manifest of the rendered load operations. Generated by `render --write`; do not edit.\n");
        sb.Append($"model: {YamlText.Scalar(model)}\ntarget: {target}\ndefinition_hash: {definitionHash}\n");
        sb.Append("sources: ").Append(YamlText.FlowList(sources)).Append('\n');
        sb.Append("operations:\n");
        foreach (var op in operations.OrderBy(o => o.Name, StringComparer.Ordinal))
        {
            sb.Append($"  - name: {op.Name}\n    default: {(op.IsDefault ? "true" : "false")}\n    strategy: {op.Strategy}\n    transactional: true\n    matrix: {op.Matrix}\n");
            sb.Append("    findings: ").Append(YamlText.FlowList(op.Findings)).Append('\n');
            sb.Append($"    script: {op.ScriptFile}\n    script_sha256: {op.ScriptSha256}\n");
            if (op.ResolverFile != null) sb.Append($"    resolver: {op.ResolverFile}\n    resolver_sha256: {op.ResolverSha256}\n");
            if (op.Parameters.Count == 0) sb.Append("    parameters: []\n");
            else
            {
                sb.Append("    parameters:\n");
                foreach (var p in op.Parameters)
                    sb.Append($"      - name: {p.Name}\n        type: {YamlText.Scalar(p.Type)}\n        source: {p.Source}\n").Append(p.Constraint == null ? "" : $"        constraint: {YamlText.Scalar(p.Constraint)}\n");
            }
        }
        return sb.ToString();
    }
}
