using System.Text.Json;

namespace DbDataBuild.Sql.Ast;

/// <summary>
/// A node of polyglot's JSON AST. The wire format is externally tagged: a node is an object with exactly one property
/// whose value is an object (<c>{"cast": {...fields...}}</c>). Fields hold child nodes, arrays of nodes, or plain data.
/// </summary>
public sealed class AstNode
{
    public string Type { get; }
    public JsonElement Body { get; }
    public AstNode? Parent { get; }
    public IReadOnlyList<AstNode> Children => children;
    private readonly List<AstNode> children = [];

    /// <summary>Tags of polyglot's Expression variants (generated by scripts/gen-ast-types.sh). Anything else is a field name.</summary>
    public static readonly IReadOnlySet<string> KnownTypes = LoadKnownTypes();

    private static HashSet<string> LoadKnownTypes()
    {
        using var stream = typeof(AstNode).Assembly.GetManifestResourceStream("expression-types.txt")
            ?? throw new InvalidOperationException("expression-types.txt is not embedded.");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd().Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Where(l => !l.StartsWith('#')).ToHashSet(StringComparer.Ordinal);
    }

    private AstNode(string type, JsonElement body, AstNode? parent) { Type = type; Body = body; Parent = parent; }

    /// <summary>Parses the array returned by <c>polyglot_parse</c>. Statements become the roots' children of a synthetic "root" node.</summary>
    public static AstNode Parse(string json)
    {
        using var doc = JsonDocument.Parse(json);
        var root = new AstNode("root", default, null);
        Visit(doc.RootElement.Clone(), root);
        return root;
    }

    private static void Visit(JsonElement value, AstNode parent)
    {
        switch (value.ValueKind)
        {
            case JsonValueKind.Array:
                foreach (var e in value.EnumerateArray()) Visit(e, parent);
                break;
            case JsonValueKind.Object:
                if (IsNode(value, out var type, out var body))
                {
                    var node = new AstNode(type, body, parent);
                    parent.children.Add(node);
                    foreach (var p in body.EnumerateObject()) Visit(p.Value, node);
                }
                else
                {
                    foreach (var p in value.EnumerateObject()) Visit(p.Value, parent);
                }
                break;
        }
    }

    private static bool IsNode(JsonElement obj, out string type, out JsonElement body)
    {
        type = ""; body = default;
        JsonProperty? only = null;
        foreach (var prop in obj.EnumerateObject())
        {
            if (only != null) return false;
            only = prop;
        }
        if (only is not { } p || p.Value.ValueKind != JsonValueKind.Object || !KnownTypes.Contains(p.Name)) return false;
        type = p.Name; body = p.Value;
        return true;
    }

    public IEnumerable<AstNode> Descendants()
    {
        foreach (var c in children)
        {
            yield return c;
            foreach (var d in c.Descendants()) yield return d;
        }
    }

    public IEnumerable<AstNode> DescendantsAndSelf() => Descendants().Prepend(this);

    public bool TryGet(string field, out JsonElement value)
    {
        value = default;
        return Body.ValueKind == JsonValueKind.Object && Body.TryGetProperty(field, out value);
    }

    public string? GetString(string field) =>
        TryGet(field, out var v) && v.ValueKind == JsonValueKind.String ? v.GetString() : null;

    /// <summary>First source position found in this node's subtree (1-based line and column), or (0, 0).</summary>
    public (int Line, int Column) Location() => Body.ValueKind == JsonValueKind.Object ? FirstSpan(Body) ?? (0, 0) : (0, 0);

    /// <summary>Position of the first span inside one field of this node (for example the QUALIFY clause of a select), or null.</summary>
    public (int Line, int Column)? LocationOfField(string field) =>
        TryGet(field, out var v) ? FirstSpan(v) : null;

    private static (int, int)? FirstSpan(JsonElement e)
    {
        switch (e.ValueKind)
        {
            case JsonValueKind.Object:
                if (e.TryGetProperty("span", out var span) && span.ValueKind == JsonValueKind.Object &&
                    span.TryGetProperty("line", out var l) && span.TryGetProperty("column", out var c))
                    return (l.GetInt32(), c.GetInt32());
                foreach (var p in e.EnumerateObject())
                    if (FirstSpan(p.Value) is { } found) return found;
                return null;
            case JsonValueKind.Array:
                foreach (var item in e.EnumerateArray())
                    if (FirstSpan(item) is { } found) return found;
                return null;
            default:
                return null;
        }
    }
}
