using DbDataBuild.Cli;
using static DbDataBuild.Tests.Unit.TestSupport;

namespace DbDataBuild.Tests.Unit;

/// <summary>The lowering stage inside the commands: the committed artifact, what it changes about findings, and its refusals.</summary>
public class LoweringIntegrationTests
{
    private const string Orders = "name: staging.orders\nkind:\n  type: mapped\ngrain: [order_id]\ncolumns:\n  - {name: order_id, type: BIGINT, nullable: false}\n  - {name: customer_id, type: BIGINT}\n  - {name: amount, type: \"DECIMAL(14, 2)\"}\n";
    private const string Fct = "name: marts.fct\nkind: {type: full}\nconnections: [sqlserver]\ncolumns:\n  - {name: customer_id, type: BIGINT}\n  - {name: n, type: BIGINT}\n";

    private static string Project(string sql, string config = "defaults: {connections: [sqlserver]}\n")
    {
        var dir = NewProjectDir();
        Directory.CreateDirectory(Path.Combine(dir, "models/staging"));
        File.WriteAllText(Path.Combine(dir, "models/staging/orders.yml"), Orders);
        File.WriteAllText(Path.Combine(dir, "dbdatabuild.yml"), config);
        File.WriteAllText(Path.Combine(dir, "models/marts/fct.yml"), Fct);
        File.WriteAllText(Path.Combine(dir, "models/marts/fct.sql"), sql);
        return dir;
    }

    private static (int Exit, string Out, string Err) Run(params string[] args)
    {
        var o = new StringWriter(); var e = new StringWriter();
        return (CliApp.Run(args, o, e, environment: _ => null), o.ToString(), e.ToString());
    }

    private const string Grouped = "SELECT customer_id, COUNT(*) AS n FROM staging.orders GROUP BY ALL\n";

    [Fact]
    public void Render_writes_a_lowered_artifact_with_a_header_that_names_its_source_and_the_engine_version()
    {
        var dir = Project(Grouped);
        var (exit, _, err) = RenderFiles("--write", "--project", dir);
        Assert.True(exit == 0, err);
        var text = File.ReadAllText(Path.Combine(dir, "rendered/lowered/marts.fct/lowered.sql"));
        Assert.StartsWith("-- dbdatabuild lowered query. Generated by `project compile`; do not edit.\n", text);
        Assert.Contains("-- model:        marts.fct\n", text);
        Assert.Contains("-- source:       models/marts/fct.sql\n", text);
        Assert.Matches("-- source hash:  [0-9a-f]{64}\n", text);
        Assert.Matches(@"-- duckdb:       v\d+\.\d+\.\d+", text);
        Assert.Contains("-- output:       customer_id BIGINT, n BIGINT\n", text);
        Assert.EndsWith("SELECT customer_id, count(*) AS n\nFROM staging.orders\nGROUP BY customer_id\n", text);   // GROUP BY ALL is gone
        Assert.Contains("GROUP BY customer_id", File.ReadAllText(Path.Combine(dir, "rendered/sqlserver/marts.fct/load.default.sql")));
    }

    [Fact]
    public void A_stale_or_missing_lowered_file_is_a_stale_rendered_file()
    {
        var dir = Project(Grouped);
        RenderFiles("--write", "--project", dir);
        Assert.Equal(0, RenderFiles("--project", dir, "--check").Exit);
        var file = Path.Combine(dir, "rendered/lowered/marts.fct/lowered.sql");
        File.AppendAllText(file, "-- hand edit\n");
        var edited = RenderFiles("--project", dir, "--check");
        Assert.Equal(1, edited.Exit);
        Assert.Contains("DDB-424", edited.Err);
        Assert.Contains("rendered/lowered/marts.fct/lowered.sql", edited.Err);
        File.Delete(file);
        Assert.Contains("is missing", RenderFiles("--project", dir, "--check").Err);
        Assert.Equal(0, RenderFiles("--write", "--project", dir).Exit);
        Assert.Equal(0, RenderFiles("--project", dir, "--check").Exit);

        // changing the author's query changes the lowered file
        File.WriteAllText(Path.Combine(dir, "models/marts/fct.sql"), "SELECT customer_id, COUNT(*) AS n FROM staging.orders WHERE amount > 0 GROUP BY ALL\n");
        Assert.Equal(1, RenderFiles("--project", dir, "--check").Exit);
    }

    [Fact]
    public void The_removed_model_leaves_no_stale_lowered_file_behind()
    {
        var dir = Project(Grouped);
        RenderFiles("--write", "--project", dir);
        File.Delete(Path.Combine(dir, "models/marts/fct.sql")); File.Delete(Path.Combine(dir, "models/marts/fct.yml"));
        var (exit, output, _) = RenderFiles("--write", "--project", dir);
        Assert.Equal(0, exit);
        Assert.Contains("removed rendered/lowered/marts.fct/lowered.sql", output);
        Assert.False(Directory.Exists(Path.Combine(dir, "rendered/lowered/marts.fct")));
    }

    [Theory]
    [InlineData("SELECT customer_id, COUNT(*) AS n FROM staging.orders GROUP BY 1")]
    [InlineData("SELECT customer_id, COUNT(*) AS n FROM staging.orders GROUP BY ALL")]
    public void Constructs_the_binder_expands_are_no_longer_findings_on_sql_server(string sql)
    {
        var dir = Project(sql);
        var on = Run("project", "compile", "--project", dir);
        Assert.Equal(0, on.Exit);
        Assert.DoesNotContain("DDB-301", on.Err);

        // turning lowering off restores the old behavior: the author's text goes to the matrix as written, and a project with errors is not compiled
        Directory.Delete(Path.Combine(dir, "rendered"), true);
        File.WriteAllText(Path.Combine(dir, "dbdatabuild.yml"), "defaults: {connections: [sqlserver]}\nlowering:\n  enabled: false\n");
        var off = Run("project", "compile", "--project", dir);
        Assert.Equal(1, off.Exit);
        Assert.Contains("DDB-301", off.Err);
        Assert.False(Directory.Exists(Path.Combine(dir, "rendered")));
    }

    [Fact]
    public void With_lowering_off_no_lowered_file_is_written()
    {
        var dir = Project("SELECT customer_id, COUNT(*) AS n FROM staging.orders GROUP BY customer_id\n", "defaults: {connections: [sqlserver]}\nlowering:\n  enabled: false\n");
        Assert.Equal(0, RenderFiles("--write", "--project", dir).Exit);
        Assert.False(Directory.Exists(Path.Combine(dir, "rendered/lowered")));
        Assert.True(File.Exists(Path.Combine(dir, "rendered/sqlserver/marts.fct/load.default.sql")));
    }

    [Theory]
    [InlineData("SELECT customer_id, [1, 2] AS l FROM staging.orders", "DDB-324", "list_value")]
    [InlineData("SELECT DISTINCT ON (customer_id) customer_id, order_id FROM staging.orders", "DDB-324", "DISTINCT ON")]
    [InlineData("SELEC customer_id FROM staging.orders", "DDB-306", "syntax error")]
    [InlineData("SELECT customer_id FROM staging.missing", "DDB-218", "missing")]
    public void A_query_that_cannot_be_lowered_is_an_error_that_names_why_and_nothing_is_written(string sql, string code, string mention)
    {
        var dir = Project(sql);
        var (exit, _, err) = RenderFiles("--write", "--project", dir);
        Assert.Equal(1, exit);
        Assert.Contains(code, err);
        Assert.Contains(mention, err, StringComparison.OrdinalIgnoreCase);
        Assert.False(Directory.Exists(Path.Combine(dir, "rendered")));
        Assert.Equal(1, Run("project", "compile", "--project", dir).Exit);
    }

    [Fact]
    public void Correlated_subqueries_are_lowered_and_checked_like_any_other_query()
    {
        var dir = Project("SELECT o.customer_id, (SELECT count(*) FROM staging.orders p WHERE p.customer_id = o.customer_id) AS n FROM staging.orders o WHERE EXISTS (SELECT 1 FROM staging.orders q WHERE q.customer_id = o.customer_id AND q.amount > 10)\n");
        var (exit, _, err) = RenderFiles("--write", "--project", dir);
        Assert.True(exit == 0, err);
        var text = File.ReadAllText(Path.Combine(dir, "rendered/lowered/marts.fct/lowered.sql"));
        Assert.Contains("EXISTS (", text);
        Assert.Equal(2, System.Text.RegularExpressions.Regex.Matches(text, @"\([pq]\.customer_id = o\.customer_id\)").Count);   // the outer column is qualified inside each subquery, by the aliases the author wrote
        Assert.Contains("FROM staging.orders AS o\nWHERE EXISTS", text);                                                           // and the outer block names its table once
        Assert.DoesNotContain("DELIM", text);
        Assert.Contains("EXISTS", File.ReadAllText(Path.Combine(dir, "rendered/sqlserver/marts.fct/load.default.sql")), StringComparison.OrdinalIgnoreCase);
        Assert.Equal(0, RenderFiles("--project", dir, "--check").Exit);
    }

    [Fact]
    public void DISTINCT_ON_is_lowered_when_the_ordering_includes_the_declared_grain_and_refused_otherwise()
    {
        // staging.orders declares grain [order_id]
        var ok = Project("SELECT DISTINCT ON (customer_id) customer_id, order_id AS n FROM staging.orders ORDER BY customer_id, amount DESC, order_id\n");
        var (exit, _, err) = RenderFiles("--write", "--project", ok);
        Assert.True(exit == 0, err);
        Assert.Contains("row_number() OVER (PARTITION BY customer_id ORDER BY amount DESC NULLS LAST, order_id NULLS LAST)", File.ReadAllText(Path.Combine(ok, "rendered/lowered/marts.fct/lowered.sql")));

        var ties = Project("SELECT DISTINCT ON (customer_id) customer_id, order_id AS n FROM staging.orders ORDER BY customer_id, amount DESC\n");
        var refused = RenderFiles("--write", "--project", ties);
        Assert.Equal(1, refused.Exit);
        Assert.Contains("DDB-324", refused.Err);
        Assert.Contains("add the grain column(s) `order_id` of `staging.orders` to its ORDER BY", refused.Err);
        Assert.False(Directory.Exists(Path.Combine(ties, "rendered")));
    }

    [Fact]
    public void Metadata_carries_the_types_the_plan_resolved_and_the_rules_that_changed_the_text()
    {
        var dir = Project("SELECT customer_id, AVG(amount) AS n FROM staging.orders GROUP BY ALL\n");
        var o = new StringWriter();
        Assert.Equal(0, CliApp.Run(["project", "show", "metadata", "--project", dir, "--format", "json"], o, new StringWriter(), environment: _ => null));
        var model = System.Text.Json.Nodes.JsonNode.Parse(o.ToString())!["data"]!["models"]![0]!;
        Assert.Equal("DOUBLE", (string?)model["columns"]!.AsArray().Single(c => (string?)c!["name"] == "n")!["duckdb_type"]);
        Assert.Equal("BIGINT", (string?)model["columns"]!.AsArray().Single(c => (string?)c!["name"] == "customer_id")!["duckdb_type"]);
        Assert.Equal("avg-double", (string?)model["lowered"]!["rules"]![0]);
        Assert.Equal("rendered/lowered/marts.fct/lowered.sql", (string?)model["lowered"]!["file"]);
        Assert.Matches("^[0-9a-f]{64}$", (string?)model["lowered"]!["hash"]);
    }

    private static string Lowered(string sql)
    {
        var dir = Project(sql + "\n");
        var (exit, _, err) = RenderFiles("--write", "--project", dir);
        Assert.True(exit == 0, err);
        return File.ReadAllText(Path.Combine(dir, "rendered/lowered/marts.fct/lowered.sql"));
    }

    [Fact]
    public void The_aliases_the_author_wrote_for_tables_come_back_in_the_lowered_query()
    {
        var text = Lowered("SELECT a.order_id, b.order_id AS other FROM staging.orders a JOIN staging.orders b ON b.customer_id = a.customer_id AND b.order_id <> a.order_id");
        Assert.Contains("FROM staging.orders AS a\nJOIN staging.orders AS b", text);
        Assert.Contains("(a.customer_id = b.customer_id) AND (a.order_id <> b.order_id)", text);
        Assert.DoesNotContain("orders_2", text);
    }

    [Fact]
    public void A_table_mentioned_without_an_alias_keeps_its_own_name_even_after_an_aliased_mention()
    {
        var text = Lowered("SELECT x.order_id, orders.order_id AS other FROM staging.orders x JOIN staging.orders ON orders.customer_id = x.customer_id");
        Assert.Contains("staging.orders AS x", text);
        Assert.Contains("JOIN staging.orders\n", text);                                 // the second mention has no alias, and is not called orders_2
        Assert.Contains("(x.customer_id = orders.customer_id)", text);
    }

    [Fact]
    public void A_query_with_a_cte_is_lowered_with_the_tables_own_names_because_the_plan_uses_a_cte_once_per_use()
    {
        var text = Lowered("WITH big AS (SELECT * FROM staging.orders o WHERE o.amount > 10) SELECT big.order_id, other.order_id AS o2 FROM big JOIN big AS other ON other.customer_id = big.customer_id");
        Assert.DoesNotContain(" AS o\n", text);
        Assert.DoesNotContain("orders AS o ", text);
    }
}
