<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DbDataBuild.Core\DbDataBuild.Core.csproj" />
    <ProjectReference Include="..\DbDataBuild.Models\DbDataBuild.Models.csproj" />
    <ProjectReference Include="..\DbDataBuild.Sql\DbDataBuild.Sql.csproj" />
    <ProjectReference Include="..\DbDataBuild.Define\DbDataBuild.Define.csproj" />
    <ProjectReference Include="..\DbDataBuild.Targets\DbDataBuild.Targets.csproj" />
    <ProjectReference Include="..\DbDataBuild.State\DbDataBuild.State.csproj" />
    <ProjectReference Include="..\DbDataBuild.Execution\DbDataBuild.Execution.csproj" />
    <ProjectReference Include="..\DbDataBuild.Planning\DbDataBuild.Planning.csproj" />
    <ProjectReference Include="..\DbDataBuild.Apply\DbDataBuild.Apply.csproj" />
    <ProjectReference Include="..\DbDataBuild.Lowering\DbDataBuild.Lowering.csproj" />
    <ProjectReference Include="..\DbDataBuild.Sample\DbDataBuild.Sample.csproj" />
    <ProjectReference Include="..\DbDataBuild.Targets.DuckDb\DbDataBuild.Targets.DuckDb.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>dbdatabuild</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
