<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DbDataBuild.Core\DbDataBuild.Core.csproj" />
    <ProjectReference Include="..\DbDataBuild.Models\DbDataBuild.Models.csproj" />
    <ProjectReference Include="..\DbDataBuild.Sql\DbDataBuild.Sql.csproj" />
    <ProjectReference Include="..\DbDataBuild.Define\DbDataBuild.Define.csproj" />
    <ProjectReference Include="..\DbDataBuild.State\DbDataBuild.State.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.TransactSql.ScriptDom" Version="180.117.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
