#!/usr/bin/env bash
# Generates src/DbDataBuild.Sql/Ast/expression-types.txt: the JSON tag of every polyglot `Expression` variant
# (serde rename_all = "snake_case"), read from the pinned checkout. The AST walker needs it to tell node tags from
# field names. Re-run after changing the pin. Usage: scripts/gen-ast-types.sh [polyglot-checkout]
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="${1:-$ROOT/.build/polyglot}/crates/polyglot-sql/src/expressions.rs"
PIN="$(grep -oP '^PIN="\K[0-9a-f]+' "$ROOT/scripts/build-polyglot.sh")"
OUT="$ROOT/src/DbDataBuild.Sql/Ast/expression-types.txt"
{
  echo "# polyglot-sql Expression variant tags (snake_case). Generated by scripts/gen-ast-types.sh. Do not edit."
  echo "# pin: $PIN"
  awk '/^pub enum Expression \{/{f=1;next} f&&/^\}/{exit} f&&/^    [A-Z][A-Za-z0-9]*\(/{
         match($0, /[A-Z][A-Za-z0-9]*/); v=substr($0, RSTART, RLENGTH); out="";
         for(i=1;i<=length(v);i++){c=substr(v,i,1); if(i>1&&c~/[A-Z]/) out=out "_"; out=out tolower(c)}
         print out }' "$SRC" | sort -u
} > "$OUT"
echo "Wrote $(grep -vc '^#' "$OUT") tags to $OUT"
